# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Dev and PR

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:  
        fetch-depth: 0  
    
    - name: Github Tag with semantic versioning
      id: tag_version
      uses: hennejg/github-tag-action@v4.2.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main
        dry_run: "true"

    - name: Replace Action
      uses: datamonsters/replace-action@v2
      with:
        files: 'src/main/java/net/petercashel/RealmsOfAvalonMod/RealmsOfAvalonMod.java'
        replacements: '1.0.2.4=${{ steps.tag_version.outputs.new_version }}'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        GITTAG: ${{ steps.tag_version.outputs.new_tag }}
      run: ./gradlew -b buildci.gradle build
    
    - uses: actions/upload-artifact@v2
      with:
        name: realmsofavalonmod-${{ steps.tag_version.outputs.new_tag }}.jar
        path: build/libs/realmsofavalonmod-${{ steps.tag_version.outputs.new_tag }}.jar

