# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release Builds

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    environment: Release

    steps:
    - uses: actions/checkout@v2
      with:  
        fetch-depth: 0  
    
    - name: Github Tag with semantic versioning
      id: tag_version
      uses: hennejg/github-tag-action@v4.2.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main
        
    - name: Generate Changelog
      id: changelog
      uses: Helmisek/conventional-changelog-generator@v1.0.4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        commit-types: "fix:Bug Fixes,feat:Features,refactor:Refactoring,change:Changes,build:Build Process,ci:Build Process,break:BREAKING CHANGE,BREAKING CHANGE:BREAKING CHANGE"
            
    - name: echo changelog
      run: echo "${{ steps.changelog.outputs.changelog }}"
    
    - name: Merge into Dev
      uses: everlytic/branch-merge@1.1.0
      with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'dev'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
        
    - name: Replace Action
      uses: datamonsters/replace-action@v2
      with:
        files: 'src/main/java/net/petercashel/RealmsOfAvalonMod/RealmsOfAvalonMod.java'
        replacements: '1.0.2.4=${{ steps.tag_version.outputs.new_version }}'
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        GITTAG: ${{ steps.tag_version.outputs.new_tag }}
      run: ./gradlew -b buildci.gradle build
    
#     - uses: actions/upload-artifact@v2
#       with:
#         name: Package
#         path: build/libs

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.changelog.outputs.changelog }}
        #body_path: ./changelog.txt
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: build/libs/realmsofavalonmod-${{ steps.tag_version.outputs.new_tag }}-sources.jar
        asset_name: realmsofavalonmod-${{ steps.tag_version.outputs.new_tag }}-sources.jar
        asset_content_type: application/java-archive
        
    - name: Upload Release Asset 2
      id: upload-release-asset2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: build/libs/realmsofavalonmod-${{ steps.tag_version.outputs.new_tag }}.jar
        asset_name: realmsofavalonmod-${{ steps.tag_version.outputs.new_tag }}.jar
        asset_content_type: application/java-archive
    
    - name: Release to CurseForge
      id: cfupload
      uses: itsmeow/curseforge-upload@v3
      with:
        token: ${{ secrets.CURSEFORGEAPI }}
        project_id: 430049
        game_endpoint: minecraft
        file_path: build/libs/realmsofavalonmod-${{ steps.tag_version.outputs.new_tag }}.jar
        changelog: ${{ steps.changelog.outputs.changelog }} \n Github Actions Automated Upload from ${{ steps.create_release.outputs.html_url }}
        display_name: Realms of Avalon Mod ${{ steps.tag_version.outputs.new_version }}
        game_versions: minecraft-1-12:1.12.2,Java 8,Forge
        release_type: alpha
        relations: cofh-core:requiredDependency,redstone-flux:requiredDependency,thermal-foundation:requiredDependency,thermal-expansion:requiredDependency
